logging.level:
  root: TRACE
  org.springframework.cloud.gateway: TRACE
  reactor.netty.http.client: DEBUG



spring:
  cloud:
    gateway:
      routes:
        - id: service_route
          uri: http://localhost:8081
          predicates:
            - Path=/service/**
          filters:
            - RewritePath=/service(?<segment>/?.*), $\{segment}